---
ID: "922000f2-85f9-4fe5-9a27-bec1c80edbce"
Parent: "40a4a8e7-4adf-4717-a5a7-395396befa91"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/SF/Feature/Analytics/Configuration Templates
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170917T213816Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
