---
ID: "2aed0a17-bf1c-4caa-aead-d64646e804c2"
Parent: "a02bd404-6169-46ed-8226-41bef6c04e8b"
Template: "a02bd404-6169-46ed-8226-41bef6c04e8b"
Path: /sitecore/templates/Feature/SF/Composite/Rendering Parameters/Composite Component Rendering Parameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171020T000404Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c4b33794-786a-4d37-88f8-fa9ffc23247d"
      Hint: Enable Async
      Type: Checkbox
      Value: 1
