---
ID: "e9566cb5-78cd-43cc-bf86-478a37cc64f1"
Parent: "aa343bbd-3952-4951-8480-2204508fc3ca"
Template: "aa343bbd-3952-4951-8480-2204508fc3ca"
Path: /sitecore/templates/Feature/SF/Handlebars/Component Templates/HandlebarTemplate/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161103T124450Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
