---
ID: "6dbb35e8-a8b0-4348-880e-ebd08dc3a173"
Parent: "67c618be-6fe8-4156-a677-1109485f6300"
Template: "67c618be-6fe8-4156-a677-1109485f6300"
Path: /sitecore/templates/Feature/SF/Handlebars/Folder Templates/Handlebar Template Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {67C618BE-6FE8-4156-A677-1109485F6300}
    {AA343BBD-3952-4951-8480-2204508FC3CA}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T091628
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
