---
ID: "d6dde376-b054-4cde-8163-cef4608ca63f"
Parent: "7429be64-f183-4748-9c2c-6a01d9c63a06"
Template: "7429be64-f183-4748-9c2c-6a01d9c63a06"
Path: /sitecore/templates/Feature/SF/Handlebars/Component Templates/HandlebarJsonContainer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160914T200956Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
