---
ID: "7d65b47b-ae48-4c38-8504-c08782d31205"
Parent: "69dba5a6-8f69-4970-b0a0-3f46450f40f5"
Template: "69dba5a6-8f69-4970-b0a0-3f46450f40f5"
Path: /sitecore/templates/Foundation/SF/Components/Rendering Variant/View Rendering/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180201T134649Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
