---
ID: "005d3ae9-b8c1-44a1-b241-5c1adb05d9bd"
Parent: "c4e5d134-d01c-4a46-a1d3-76d615ad0a3e"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Foundation/SF/Configuration/Folder Templates/Site Settings Folder
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/32x32/gear.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{A87A00B1-E6DB-45AB-8B54-636FEC3B5523}"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{1815C251-91AB-480D-BC6E-DF6031F6E969}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180203T204038Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
