---
ID: "5ea24ee2-6a50-46a7-a242-bae760aa27d8"
Parent: "4d132935-8652-41be-88cd-9eacddecfcce"
Template: "4d132935-8652-41be-88cd-9eacddecfcce"
Path: /sitecore/templates/Feature/SF/Handlebars/Component Templates/HandlebarQueryContainer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1ccf4493-2be2-4781-87ff-435cee46f8ee"
      Hint: Enable Pagination
      Type: Checkbox
      Value: 1
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151113T134822
    - ID: "28e75308-c5c1-4634-97ee-27d5f2987ef3"
      Hint: Query Parameter
      Value: q
    - ID: "4059aa36-9451-4276-ae59-4403877d764c"
      Hint: Querystring Parameter
      Value: page
    - ID: "4d0c1825-d352-4498-b20d-e9e8e20eaea5"
      Hint: Items Per Page
      Value: 10
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "bc920248-e3ed-4603-834e-846f8970c640"
      Hint: Order By Direction
      Value: Ascending
