---
ID: "19206bfb-91b5-4f61-a269-c14bb99cd237"
Parent: "9c122042-49aa-41c1-8320-4bfa2b97fa5a"
Template: "9c122042-49aa-41c1-8320-4bfa2b97fa5a"
Path: /sitecore/templates/Feature/SF/Handlebars/Folder Templates/Handlebar Form Processors Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {97BE8FD4-CDD6-495C-B697-E293473B5251}
    {667C146A-F8DE-44F1-ABBC-B05FC7107B90}
    {9C122042-49AA-41C1-8320-4BFA2B97FA5A}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T091628
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
