---
ID: "b9b67d41-391e-46d1-9b3d-3734a1cc40fa"
Parent: "46fb120d-8d64-4f62-b8f3-40fb97b625d8"
Template: "46fb120d-8d64-4f62-b8f3-40fb97b625d8"
Path: /sitecore/templates/SF/Feature/Handlebars/Component Templates/HandlebarForm/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171016T001722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
