---
ID: "57a856cd-ba67-4de8-a8de-9c0e2e3c3d3e"
Parent: "46fb120d-8d64-4f62-b8f3-40fb97b625d8"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/SF/Handlebars/Component Templates/HandlebarForm/Handlebar Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171016T000514Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
