---
ID: "be0e3c06-cfdd-4985-b1b1-50cb9e8d1b0a"
Parent: "97be8fd4-cdd6-495c-b697-e293473b5251"
Template: "97be8fd4-cdd6-495c-b697-e293473b5251"
Path: /sitecore/templates/Feature/SF/Handlebars/Form Processors/User Settings Processor/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171016T000730Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5eb4d348-8799-4340-a6b3-6e7dde962e9c"
      Hint: Type
      Value: SF.Feature.Handlebars.UserSettingsFormProcessor,SF.Feature.Handlebars
