---
ID: "f98d13d6-d8a6-4dda-b1e6-1fea7f40dbe0"
Parent: "4762387e-b141-421e-a26e-824125909a69"
Template: "4762387e-b141-421e-a26e-824125909a69"
Path: /sitecore/templates/SF/Feature/Handlebars/Rendering Parameters/AddNewItemRenderingParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150509T160917
