---
ID: "6858452b-8738-47ab-8713-891267ebc745"
Parent: "09831869-d73d-4ea1-b585-a7ae47d0bcc7"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/SF/Foundation/Multisite/Interface Templates/_MultisitePageSettings/Multi Site Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140912T093232
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
