---
ID: "fac65cfa-4cb5-40ba-adae-95ef6f41f364"
Parent: "2a5e5a83-7d9b-4812-ac65-3ea9f32026b3"
Template: "2a5e5a83-7d9b-4812-ac65-3ea9f32026b3"
Path: /sitecore/templates/SF/Feature/FoundationComponents/Rendering Parameters/IconBarItemParameters/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T232405
