---
ID: "b981b8a3-a929-4f45-bfe6-cbbf7f8ea817"
Parent: "7a71c555-c114-4dc3-a0a1-f5d84d1baa8d"
Template: "7a71c555-c114-4dc3-a0a1-f5d84d1baa8d"
Path: /sitecore/templates/Feature/SF/Handlebars/Folder Templates/Handlebar Forms Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {46FB120D-8D64-4F62-B8F3-40FB97B625D8}
    {7A71C555-C114-4DC3-A0A1-F5D84D1BAA8D}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T131628Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
